
import java.io.File;
import java.util.ArrayList;
import static java.util.Arrays.asList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrator
 */
public class ImageInFrom extends javax.swing.JFrame {

    /**
     * Creates new form ImageInFrom
     */
    public ImageInFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImage = new javax.swing.JLabel();
        jButtonNext = new javax.swing.JButton();
        jButtonPrev = new javax.swing.JButton();
        jButtonSelectDir = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pussycat1.jpg"))); // NOI18N

        jButtonNext.setText("Další");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonPrev.setText("Předchozí");
        jButtonPrev.setEnabled(false);
        jButtonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevActionPerformed(evt);
            }
        });

        jButtonSelectDir.setText("Vybrat adresář");
        jButtonSelectDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectDirActionPerformed(evt);
            }
        });

        jLabelInfo.setText("k dispozici jsou interní obrázky");

        jLabel1.setText("Info:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImage)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPrev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelectDir)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelInfo)))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonNext, jButtonPrev});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrev)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonSelectDir)
                    .addComponent(jLabelInfo)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImage)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    List<String> obrazky = new ArrayList<>(
            asList("images/pussycat1.jpg", "images/cat2.png", "images/3.jpg"));
    int index = 0;
    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        String path = obrazky.get(index);
        jLabelInfo.setText(path);
        ImageIcon iic;
        if (obrazky.get(index).startsWith("images/")) {
            iic = new ImageIcon(getClass().getResource(path));
        } else {
            iic = new ImageIcon(path);
        }
        jLabelImage.setIcon(iic);
        if (index < obrazky.size() - 1) {
            index++;
        } else 
            jButtonNext.setEnabled(false);
        jButtonPrev.setEnabled(true);
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevActionPerformed
        if (index > 0) {
            index--;
            jButtonNext.setEnabled(true);
        }
        if (index == 0) jButtonPrev.setEnabled(false);
        String path = obrazky.get(index);
        jLabelInfo.setText(path);
        ImageIcon iic;
        if (obrazky.get(index).startsWith("images/")) {
            iic = new ImageIcon(getClass().getResource(path));
        } else {
            iic = new ImageIcon(path);
        }
        jLabelImage.setIcon(iic);
    }//GEN-LAST:event_jButtonPrevActionPerformed

    File directory = null;
    private void jButtonSelectDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectDirActionPerformed
        JFileChooser fc = new JFileChooser();
        // uživatel musí vybrat adresář
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        // otevření dialogu
        int retVal = fc.showOpenDialog(null);
        // vyhodnocení výběru uživatele
        if (retVal == JFileChooser.APPROVE_OPTION) {
            directory = fc.getSelectedFile();
            int pocet = 0;
            for (final File fileEntry : directory.listFiles()) {
                if (fileEntry.isFile()
                        && (fileEntry.getName().endsWith(".jpg")
                        || fileEntry.getName().endsWith(".gif")
                        || fileEntry.getName().endsWith(".png"))) {
                    obrazky.add(fileEntry.getAbsolutePath());
                    pocet++;
                }
            }
            jLabelInfo.setText("Adresář " + directory.getPath()
                + " (+" + pocet + ")");
            jButtonNext.setEnabled(true);
        } else {
            jLabelInfo.setText("výběr zrušen uživatelem.");
        }
    }//GEN-LAST:event_jButtonSelectDirActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                



}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageInFrom.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 



catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageInFrom.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 



catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageInFrom.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 



catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageInFrom.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageInFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JButton jButtonSelectDir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelInfo;
    // End of variables declaration//GEN-END:variables
}
